apiVersion: apps/v1
kind: Deployment
metadata:
  name: concourse-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: concourse-worker
  template:
    metadata:
      labels:
        app: concourse-worker
    spec:
      containers:
        - name: concourse-worker
          image: concourse/concourse:latest
          # ... add necessary environment variables, ports, volumes, etc
