apiVersion: apps/v1
kind: Deployment
metadata:
  name: concourse-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: concourse-web
  template:
    metadata:
      labels:
        app: concourse-web
    spec:
      containers:
        - name: concourse-web
          image: concourse/concourse:latest
          args: ["web"]
          env:
            - name: CONCOURSE_POSTGRES_HOST
              value: concourse-postgres
            - name: CONCOURSE_POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: concourse-postgres-secret
                  key: user
            - name: CONCOURSE_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: concourse-postgres-secret
                  key: password
            - name: CONCOURSE_POSTGRES_DATABASE
              value: concourse
          # ... other necessary environment variables
