apiVersion: v1
kind: Secret
metadata:
  name: concourse-postgres-secret
type: Opaque
data:
  user: Y29uY291cnNlX3VzZXI= # base64 encoded username
  password: Y29uY291cnNlX3Bhc3M= # base64 encoded password
