apiVersion: apps/v1
kind: Deployment
metadata:
  name: concourse-web
spec:
  template:
    spec:
      containers:
        - name: concourse-web
          # Apply dev-specific settings here, such as resources, image tags, etc
